### PR TITLE
accept foreign key for pk

### PR DESCRIPTION
**Pull request by vasion**
Hi, I was having trouble with updating when the pk is a relation on postgres, I added a small tweak and introduced pk_attribute which is the field name if the pk is a normal field and field_name + "_id" if a relation. Hope you accept it.

### CODE REVIEW

**Comment by aykut** [comment]
Hi,

Thanks for the PR. Can you please add tests that covers this case. So we can be sure, it won't break anything in future.

Thanks.

**Comment by aykut** [comment]
I just got why you are trying to achieve but I couldn't understand why don't you just pass the `pk_field` with the "_id" suffix?

**Comment by vasion** [comment]
If you mean pass for example "user_id" to the pk_field argument in the help, it wasn't working. "user_id" for ForeignKey("User") is a db field, but not a field in the django model, so it does not appear in the _meta. Did I understand your question correctly? 

My situation is this - I have a Profile model whose primary field is a one-to-one relation to User. The result was that not only was User dereferenced, but also the entire object was being used as a param to sql, causing an exception. 

I will write some tests over the weekend.

**Comment by aykut** [comment]
Yes, that was what I meant. I see your point.

**Comment by aykut** [comment]
I think #54 fixed this one.

**Pull request closed without merging**
