### PR TITLE
quote dbtable in update query

### PR DESCRIPTION
**Pull request by torchingloom**

### CODE REVIEW

**Comment by aykut** [comment]
Can you write a description why you did this?

Thanks.

**Comment by torchingloom** [comment]
Sorry, my Eanglish is not so good.
I did it because I have table "user" in postgresql database :)

**Comment by aykut** [comment]
I got it, thanks :).

**Comment by aykut** [comment]
1.1.4 is available on pypi now.

**Comment by torchingloom** [comment]
Thats good ))

**Pull request merged**
