### PR TITLE
Allow to use bulk_update in models whose pk is an uuid.

### PR DESCRIPTION
**Pull request by arnau126**
Fixes issue #52.

### CODE REVIEW

**Comment by arnau126** [comment]
Tests fail for `django version <= 1.7` because `models.UUIDField` came up at `1.8`.
What should we do?
- Drop support for these old django versions,
- or adapt tests to only test the uuid pk if django version >= 1.8?

Any thoughts, @aykut ?

**Comment by aykut** [comment]
Thanks a lot for your support. I think it is better to workaround with the django-uuidfield package to cover django < 1.8, https://github.com/dcramer/django-uuidfield

```
try:
    from django.db.models import UUIDField
except ImportError:
    from uuidfield import UUIDField
```

What do you think?

**Comment by arnau126** [comment]
Yes, great idea. Done.

Even though, I think that a major release (`django-bulk-update==2.0.0`) is needed soon which drops support to `django<=1.7`.

I've added a commit with `tox.ini`, which is very useful for testing with different packages versions.

Please, let me know if any change is needed.

**Comment by aykut** [comment]
Thank you very much. You are right about dropping support for `django<=1.7`, if you would develop that, I am more than happy to merge it :).

**Comment by arnau126** [comment]
Thanks for the release, it will be very helpful for the project I'm working on.

Next week I'll try to work in dropping support for `django<=1.7`.

**Pull request merged**
